### PR TITLE
support working dir parameter

### PR DESCRIPTION
**Pull request by daniel-habib**
i thought it would be useful to allow users to state the working dir in which the lib works.
this can allow the lib to work without limitation of tmpfs (that are more visible on a low RAM machines/ long videos/ combination of the 2)

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Thanks for the PR @daniel-habib!

I would rather have the caller pass in `tempDir` directly instead of allowing them to pass in `workingDir` and then creating a tempDir based off of crypto randomness within that.

This means that you could have the same `workingDir` logic in your app, while keeping the ffmpeg-concat library simpler.

Lemme know if that doesn't make sense.

**Comment by transitive-bullshit** [comment]
Thanks @daniel-habib! I'm going to make a few changes after merging so your contribution is recognized :)

**Comment by daniel-habib** [comment]
makes perfect sense.
I'll send a fix today

On Jun 20, 2018 23:21, Travis Fischer <notifications@github.com> wrote:

Thanks for the PR @daniel-habib<https://github.com/daniel-habib>!

I would rather have the caller pass in tempDir directly instead of allowing them to pass in workingDir and then creating a tempDir based off of crypto randomness within that.

This means that you could have the same workingDir logic in your app, while keeping the ffmpeg-concat library simpler.

Lemme know if that doesn't make sense.

**Comment by transitive-bullshit** [comment]
Check out the current version; I made a few minor changes.

Thanks again!

**Comment by daniel-habib** [comment]
Hi

Just a quick question:
If one provides a workingDir do we implicitly assume
cleanupFrames = false
?

Otherwise we would be rimraf’ing a dir we don’t know is safe to remove…


Daniel

**Comment by transitive-bullshit** [comment]
Definitely a good question; not sure the best way to handle it.

**Pull request merged**
