### PR TITLE
Optionally select where RAW files are written to

### PR DESCRIPTION
**Pull request by BrandonCookeDev**
Recently I ran into an issue using this package: My SSD which is solely for my OS was nearly full. 
It happens that by default this package writes to the standard Temp folder in C:\ (AppData\local\Temp).

I needed the package to write to another drive, but that wasn't possible without an additional CLI option. I wrote code that added this option, and test code that verifies it works.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Hey @BrandonCookeDev, thanks for the PR!

It looks like this is the same change that @daniel-habib recently made a PR for (#16), and it's already supported.

**Comment by transitive-bullshit** [comment]
Please try the most recent master version and see if your use case is solved.  Sorry you went through all that work!

**Comment by BrandonCookeDev** [comment]
My apologies, I wasn't aware the changes had taken place so recently.
However, one of the main things I needed was a way to do this with the CLI and Daniel's PR doesn't seem to handle that case.

**Comment by BrandonCookeDev** [comment]
Well, FeelsBad I basically wrote something someone else finished writing only a day before, but it is what it is.
In any case, I think the test code should be considered for addition (with a slight tweak for Daniel's code).

**Comment by transitive-bullshit** [comment]
Yeah, I'm sorry about that @BrandonCookeDev. I'll try to merge + resolve your PR and keep the tests so your contribution is recorded.

One other thing this PR does that I like and may be a good addition is the ability to create a tempDir from the commandline within a working dir. It's a lil weird the way things are in master right now since we remove the `tempDir` passed in.

**Pull request closed without merging**
