### PR TITLE
concat source audio

### PR DESCRIPTION
**Pull request by daniel-habib**
"no-frills" audio concat.
the mode is activated when user does not provide audio file/ url.
might be a good start for #4

### CODE REVIEW

**Comment by daniel-habib** [comment]
@transitive-bullshit: why was this never merged?
am i missing something?

**Comment by transitive-bullshit** [comment]
Hey, sorry @daniel-habib -- this looks awesome. Just been busy on my end.

**Comment by transitive-bullshit** [comment]
Published as `v1.0.14`.

Thanks!!

**Comment by rana01645** [comment]
@daniel-habib thanks for the awesome solution man. 

But there is an issue. If I try to concat  a mute video with a video with audio, the final output becomes silent.  If you can look on this issue it will be great

**Comment by daniel-habib** [comment]
> 
> 
> @daniel-habib thanks for the awesome solution man.
> 
> But there is an issue. If I try to concat a mute video with a video with audio, the final output becomes silent. If you can look on this issue it will be great

let's see if i understand the facts correctly:
1/ you have more than one segments to concat.
2/ one of the segments of video you have has an audio track with mute audio on it
3/ the result is a video with mute audio 
or 
2/ one of the segments of video you have lacks audio track altogether

?

**Comment by rana01645** [comment]
The first video has no audio
Another video has audio

When I concat these two video s, the final output has no audio.

Workaround: If I add silent audio to the first video before concat.. then the problem becomes solved. Then the final video gets the audio.

Here is the command I'm using for adding silent audio to the first video
ffmpeg -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -i {{$input}} \
-shortest -c:v copy -c:a aac {{$output}}

**Comment by rana01645** [comment]
@daniel-habib 
I got another issue.

For instance:
Video x is 10 second long but it has 5 second audio
video y is 10 second long and has 3 second audio

When I concat x and y the final video only become 8 second long instead of 20 second. :(

**Comment by daniel-habib** [comment]
@rana01645 : i suggest you add a detailed bug report/ enhancement request to transitive-bullshit/ffmpeg-concat.
by detailed i mean:
1/ videos you are concating
2/ ffprobe output of each
2/ what you think is the expected behavior (e.g. if there's no audio stream at all - use an empty audio stream, if there's one audio stream and it is shorter than video fill the gap with giraffe humming)

i tend to think i'll add one of my own: 
once you could've gotten an external audio or none at all.
now you can get an external audio or original audio.
i think there's a need for 1/ an external audio 2/ original audio 3/ no audio at all.
i realize now that option 3 is a valid option as some people have been using this lib with videos whose audio is less than what this lib expects it to be,

**Pull request merged**
